### Transforming Code Into Idiomatic Python
* Replace traditional index manupulation with Python core looping idiomatic

In [2]:
# Looping over a range of numbers - Traditional Approach
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [3]:
# Idotiomatic Programming
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### Looping Over A Collection

In [7]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")


red green yellow purple 

In [6]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

###   Looping Backward

In [8]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [10]:
for color in reversed(colors):
    print(color,end=" ")
colors=['red','green','yellow','purple']


purple yellow green red green purple red yellow 

In [12]:
for color in sorted(colors):
    print(color,end=" ")

green purple red yellow 

In [14]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

### Pandas

In [15]:
import pandas as pd

In [18]:
dt={"Id":[11,12,13,14,15],
    "first_name":["A","B","C","D","E"],
   "company":["aa","bb","cc","dd","ee"],
   "address":["hyd","hyd","hyd","hyd","hyd"]}
mydt=pd.DataFrame(dt)
print(mydt)

   Id first_name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [35]:
import os

In [ ]:
os.chdir("Desktop") # saves to certain location

In [43]:
mydt.to_csv("WorkingFile.csv",index=False)

### Reading the data from CSV file

In [46]:
mydata=pd.read_csv('WorkingFile.csv',skiprows=1,
                   names=["CustID","Name","Company","Address"])

In [49]:
print(mydata)

   CustID Name Company Address
0      11    A      aa     hyd
1      12    B      bb     hyd
2      13    C      cc     hyd
3      14    D      dd     hyd
4      15    E      ee     hyd


### Print only two columns
### Print the large value from CustID column-- max
### Print the least value from CustID column -- min
### Avg of CustID column -- sum(li)/len(li)

### Numpy-Working with multi demensional array 
- Numpy array are bit like python list 
- Numpy is also one of the data structure 
- Numpy short name for "Numeric python" or "Numerical Python"

In [50]:
import numpy as np


In [52]:
li=[1,2,3,4,5]
print(li,end="")


[1, 2, 3, 4, 5]

In [53]:
array=np.array(li)
print(array)

[1 2 3 4 5]


In [55]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)


(2, 3)
(3, 2)


In [57]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [60]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
